start:
	python3 ./server.py $p $t mx-api 8888

start1:
	python3 ./server.py 8008 tv-01 mx-api 8888

start2:
	python3 ./server.py 8009 tv-02 mx-api 8888

start3:
	python3 ./server.py 8010 tv-05 mx-api 8888

start4:
	python3 ./server.py 8011 tv-06 mx-api 8888

test:
	curl http://localhost:$p
